Add verifyCommon method
LiskHQ/lisk pull request #8840
Opened 2023-08-10 14:45 UTC by sitetester

### What was the problem?

This PR resolves #8554 & #8811

### How was it solved?

LIP changes applied

### How was it tested?

Test cases updated

2023-08-11 13:04 UTC, AndreasKendziorra requested changes

2023-08-11 13:04 UTC, AndreasKendziorra commented on framework/test/unit/modules/interoperability/sidechain/commands/submit_sidechain_cross_chain_update.spec.ts
Shouldn't it be tested that `verifyCommon` is called?

2023-08-11 13:04 UTC, AndreasKendziorra commented on framework/test/unit/modules/interoperability/mainchain/commands/submit_mainchain_cross_chain_update.spec.ts
Shouldn't it be tested that `verifyCommon` is called?

2023-08-14 09:54 UTC, AndreasKendziorra commented on framework/test/unit/modules/interoperability/mainchain/commands/submit_mainchain_cross_chain_update.spec.ts
> +		it(`should verify liveness condition when sendingChainAccount.status == ${ChainStatus.REGISTERED} and inboxUpdate is empty`, async () => {
It wasn't fixed yet, right?

2023-08-14 09:56 UTC, AndreasKendziorra commented on framework/test/unit/modules/interoperability/mainchain/commands/submit_mainchain_cross_chain_update.spec.ts
> +		it(`should verify liveness condition when sendingChainAccount.status == ${ChainStatus.REGISTERED} and inboxUpdate is empty`, async () => {
oh, it is fixed. sorry

2023-08-14 15:25 UTC, ishantiw approved these changes
Adding suggestion but approving

2023-08-14 15:25 UTC, ishantiw commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		// or validatorsUpdate.bftWeightsUpdateBitmap != EMPTY_BYTES // ???
```suggestion
```

2023-08-14 16:01 UTC, merged